CREATE TABLE person (
                      id bigint generated by default as identity PRIMARY KEY,
                      name VARCHAR(255),
                      age varchar(255)
);

create table book
(
    id   VARCHAR(255) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255)
);

insert into person values (
    null, 'kim', '30'
);

insert into person values (
    null, 'lee', '20'
);

insert into person values (
    null, 'park', '10'
);